name: deploy
on:
  push:
    branches:
      - 'main'
  workflow_dispatch:

jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest

    steps:
      - name: install ssh keys
        run: install -m 600 -D /dev/null ~/.ssh/id_rsa
      - name: echo 1
        run: echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
      - name: echo 2
        run: echo "${{ secrets.SSH_HOST }}" > ~/.ssh/known_hosts
      - name: connect and pull
        run: ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "cd ${{ secrets.WORK_DIR }} && 
          git checkout ${{ secrets.MAIN_BRANCH }} &&
          git pull &&
          cd ${{secrets.NPM_DIR}} &&
          npm ci &&
          npm run build &&
          sudo rm -r /var/www/html/* &&
          sudo cp -a ${{ secrets.BUILD_DIR }} /var/www/html
          sudo systemctl restart apache2
          exit"
